version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes: 
            - ./src:/usr/app/template/src
        environment:
            - SHIHAB=false